#!/bin/sh
sudo add-apt-repository ppa:maarten-baert/simplescreenrecorder -y
sudo add-apt-repository ppa:webupd8team/sublime-text-3 -y
sudo apt-get update -y
sudo apt-get install simplescreenrecorder sublime-text-installer -y


sudo add-apt-repository ppa:indicator-multiload/stable-daily -y
sudo add-apt-repository ppa:noobslab/icons -y
sudo add-apt-repository ppa:ravefinity-project/ppa -y
sudo add-apt-repository ppa:noobslab/apps -y
sudo apt-add-repository ppa:ansible/ansible  -y
wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
sudo sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'	


sudo apt-get update -y

sudo apt-get install software-properties-common -y
sudo apt-get install indicator-multiload -y
sudo apt-get install ultra-flat-icons ultra-flat-icons-green ultra-flat-icons-orange -y
sudo apt-get install vivacious-colors -y
sudo apt-get install xdman -y
sudo apt-get install tmux -y
sudo apt-get install ibus -y
sudo apt-get install ibus-unikey -y
sudo apt-get install google-chrome-stable -y
sudo apt-get install virtualbox virtualbox-dkms vagrant virtualbox-qt -y
sudo apt-get install aria2 -y



# Install vagrant 1.7.4

Our next step is to download the latest version of both software and install it in Ubuntu 15.04. Which means we need to download DEB packages. Let's start with Vagrant. Also we need to download the corresponding checksum file as well. I'm using Aria2 instead of Wget to speed up downloading as Aria2 supports multiple simultaneous connections.
$ aria2c -x 4 https://dl.bintray.com/mitchellh/vagrant/vagrant_1.7.4_x86_64.deb
$ wget --content-disposition https://dl.bintray.com/mitchellh/vagrant/1.7.4_SHA256SUMS?direct

Before we install or upgrade Vagrant, verify the our downloaded DEB package against the checksum file. Remember to read the Changelog as well, just in case, if there are any important items relevant to our upgrade or installation.
$ sha256sum -c 1.7.4_SHA256SUMS 2>&1 | grep OK                                                                                          
vagrant_1.7.4_x86_64.deb: OK

Upgrade our Vagrant installation.
$ sudo dpkg -i vagrant_1.7.4_x86_64.deb 
......
Preparing to unpack vagrant_1.7.4_x86_64.deb ...
Unpacking vagrant (1:1.7.4) over (1:1.7.3) ...
Setting up vagrant (1:1.7.4) ...

Finally, verify our installation. See the inaccurate reporting of latest version against the installed version. Hence, to get the up-to-date version, is best to check Vagrant's download page.
$ vagrant version
Installed Version: 1.7.4
Latest Version: 1.7.3
 
You're running an up-to-date version of Vagrant!




sử dụng tiếng việt 
http://toantinit.blogspot.com/2015/08/cach-cai-ibus-unikey-tren-linux-mint-172.html

U install:
simplescreenrecorder
Multi-Load Indicator 	http://www.noobslab.com/2014/08/useful-panel-indicators-collection-for.html




http://ubuntuhandbook.org/index.php/2015/11/flatabulous-flat-theme-ubuntu/

Install fish làm mặc định 

chsh -s /usr/bin/fish

Dùng básh lại làm mặc định:
 
chsh -s /bin/bash 



