#!/bin/sh

echo "Installation starts ..."
# chỉnh font treminal la Droid Sán Môno 12

#gnome-tweak-tool, ubuntu-tweak
yes | sudo add-apt-repository ppa:tualatrix/ppa
sudo apt-get -y update
sudo apt-get -yV install ubuntu-tweak
sudo apt-get -yV install unity-tweak-tool
sudo apt-get -yV install gnome-tweak-tool

#Install apt-fast
sudo add-apt-repository ppa:saiarcot895/myppa
sudo apt-get update -y
sudo apt-get -y install apt-fast



#nautilus-open-terminal
sudo apt-get -yV install nautilus-open-terminal

# record terminal
sudo apt-add-repository ppa:zanchey/asciinema -y
sudo apt-get update -y
sudo apt-get install asciinema -y
#  2016-12-15 
# asciinema --version
# asciinema 1.3.0



sudo add-apt-repository ppa:maarten-baert/simplescreenrecorder -y
sudo add-apt-repository ppa:webupd8team/sublime-text-3 -y
sudo add-apt-repository ppa:git-core/ppa -y
sudo apt-get update -y
sudo apt-get install git simplescreenrecorder sublime-text-installer -y


Install Disk Usage Analyzer
$sudo apt-get install gksu
When the installation is finished, type the following at the prompt and press Enter to open Disk Usage Analyzer.
$gksu baobab

Install screenkey
website http://www.thregr.org/~wavexx/software/screenkey/
$sudo apt-get install python-gtk2 python-setuptools python-setuptools-git python-distutils-extra

Apply sublime-text 3 theme
https://drive.google.com/open?id=0B-niOEXlThbFR1RWajJkMzgwM0U

sudo add-apt-repository ppa:indicator-multiload/stable-daily -y
sudo add-apt-repository ppa:noobslab/icons -y
sudo add-apt-repository ppa:ravefinity-project/ppa -y
sudo add-apt-repository ppa:noobslab/apps -y
wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
sudo sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'	


sudo apt-get update -y

sudo apt-get install software-properties-common -y
sudo apt-get install indicator-multiload -y
sudo apt-get install ultra-flat-icons ultra-flat-icons-green ultra-flat-icons-orange -y
sudo apt-get install vivacious-colors -y
## download manager
sudo apt-get install xdman -y
sudo apt-get install tmux -y
sudo apt-get install ibus -y
sudo apt-get install ibus-unikey -y
sudo apt-get install google-chrome-stable -y
sudo apt-get install virtualbox virtualbox-dkms virtualbox-qt -y
sudo apt-get install vlc

wget -c https://releases.hashicorp.com/vagrant/1.8.7/vagrant_1.8.7_x86_64.deb
sudo dpkg -i ./vagrant_1.8.7_x86_64.deb
rm vagrant_1.8.7_x86_64.deb


## CLI download giong wget
$ sudo apt-get install aria2 -y
$ aria2c --version
aria2 version 1.18.1
Copyright (C) 2006, 2013 Tatsuhiro Tsujikawa


=====================================================================
#Install VirtualBox 5.1

sudo nano /etc/apt/sources.list
For Ubuntu 16.04 ("Xenial")
deb http://download.virtualbox.org/virtualbox/debian xenial contrib

For Ubuntu 15.10 ("Wily")
deb http://download.virtualbox.org/virtualbox/debian wily contrib

For Ubuntu 14.04 ("Trusty")
deb http://download.virtualbox.org/virtualbox/debian trusty contrib


$ wget -q https://www.virtualbox.org/download/oracle_vbox_2016.asc -O- | sudo apt-key add -
$ wget -q https://www.virtualbox.org/download/oracle_vbox.asc -O- | sudo apt-key add -

$ sudo apt-get update
$ sudo apt-get install virtualbox-5.1

##Confirm our installed VirtualBox version.
$ vboxmanage --version
5.1.10r112026

Lastly, if there are any Linux kernel upgrade, you may need to rebuild vboxdrv kernel module by running this command.
$ sudo /etc/init.d/vboxdrv setup
vboxdrv.sh: Building VirtualBox kernel modules.
vboxdrv.sh: Starting VirtualBox services.

=====================================================================

# Install vagrant 1.7.4

Our next step is to download the latest version of both software and install it in Ubuntu 15.04. Which means we need to download DEB packages. Let's start with Vagrant. Also we need to download the corresponding checksum file as well. I'm using Aria2 instead of Wget to speed up downloading as Aria2 supports multiple simultaneous connections.
$ aria2c -x 4 https://releases.hashicorp.com/vagrant/1.9.0/vagrant_1.9.0_x86_64.deb
$ wget --content-disposition https://releases.hashicorp.com/vagrant/1.9.0/vagrant_1.9.0_SHA256SUMS

Before we install or upgrade Vagrant, verify the our downloaded DEB package against the checksum file. Remember to read the Changelog as well, just in case, if there are any important items relevant to our upgrade or installation.
$ sha256sum -c vagrant_1.9.0_SHA256SUMS 2>&1 | grep OK                                                                                          
vagrant_1.9.0_x86_64.deb: OK

Upgrade our Vagrant installation.
$ sudo dpkg -i vagrant_1.9.0_x86_64.deb
......
Preparing to unpack vagrant_1.7.4_x86_64.deb ...
Unpacking vagrant (1:1.7.4) over (1:1.7.3) ...
Setting up vagrant (1:1.7.4) ...

Finally, verify our installation. See the inaccurate reporting of latest version against the installed version. Hence, to get the up-to-date version, is best to check Vagrant's download page.
$ vagrant version
Installed Version: 1.9.0
Latest Version: 1.9.0

 
You're running an up-to-date version of Vagrant!

=====================================================================

## INSTALL ansible

$ sudo apt-get install software-properties-common
$ sudo apt-add-repository ppa:ansible/ansible -y
$ sudo apt-get update -y
$ sudo apt-get install ansible -y

ERROR
The following packages have unmet dependencies:
 ansible : Depends: python-setuptools but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
FIX
$sudo apt-get install python-pkg-resources=3.3-1ubuntu1
$sudo apt-get install python-setuptools


## vagrant box
## Ubuntu
http://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box


sử dụng tiếng việt 
http://toantinit.blogspot.com/2015/08/cach-cai-ibus-unikey-tren-linux-mint-172.html

U install:
simplescreenrecorder
Multi-Load Indicator 	http://www.noobslab.com/2014/08/useful-panel-indicators-collection-for.html




http://ubuntuhandbook.org/index.php/2015/11/flatabulous-flat-theme-ubuntu/

##################################################################
Install Fish shell

sudo apt-add-repository ppa:fish-shell/release-2
sudo apt-get update
sudo apt-get install fish

Install fish làm mặc định 
chsh -s /usr/bin/fish

Dùng básh lại làm mặc định:
chsh -s /bin/bash 

Installing Oh My Fish:
curl -L https://github.com/oh-my-fish/oh-my-fish/raw/master/bin/install | fish

Install fisherman: A plugin manager for fish.
curl -Lo ~/.config/fish/functions/fisher.fish --create-dirs git.io/fisher

Install bobthefish theme
fisher omf/theme-bobthefish

###################################################################


Shotcut video editor:
 
sudo add-apt-repository ppa:haraldhv/shotcut -y
sudo apt-get update
sudo apt-get install shotcut -y


Install OBS 
sudo apt-add-repository ppa:kirillshkrogalev/ffmpeg-next -y
sudo apt-add-repository ppa:obsproject/obs-studio -y
sudo apt-get update -y
sudo apt-get install ffmpeg obs-studio -y

sudo apt-get install stream -y
sudo apt-get install guake -y

install mpsyt

# youtube-dl
sudo curl -L https://yt-dl.org/downloads/latest/youtube-dl -o /usr/local/bin/youtube-dl
sudo chmod a+rx /usr/local/bin/youtube-dl





